---

- name: Create extraction location
  ansible.builtin.file:
    path: /tmp/node_exporter_{{ VERSION }}
    state: directory

- name: Download and extract archive
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ VERSION }}/node_exporter-{{ VERSION }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter_{{ VERSION }}
    remote_src: true
    extra_opts: --strip-components=1

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    create_home: no
    shell: /bin/false
    system: yes
    state: present

- name: Move files to install location
  ansible.builtin.copy:
    src: /tmp/node_exporter_{{ VERSION }}/node_exporter
    dest: /usr/local/bin
    remote_src: true
    owner: node_exporter
    mode: 0744

- name: Delete extracted archive
  ansible.builtin.file:
    path: /tmp/node_exporter_{{ VERSION }}
    state: absent

- name: Create service file
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Enable Node exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes