---

  - name: Install latest python3
    apt:
      name: python3
      state: latest  
    when: version_number is undefined

  - name: "Install python3 version: {{ version_number }}"
    apt:
      name: "python3={{ version_number }}"
      state: present  
    when: version_number is not undefined

  - name: Install python 3 pip
    apt:
      name: python3-pip
      state: latest